name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight UTC
  workflow_dispatch:     # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate GitHub contribution snake

    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: bowenyu066
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}